a=int(input("Enter the number: "))
b=int(input("Enter the number: "))
print(f"Addition: {a+b}")
print(f"Subtraction: {a-b}")
print(f"Multiplication: {a*b}")
print(f"Division: {a/b}")
print(f"Remainder: {a%b}")